### ISSUE TITLE
DeepLinkHandler seriously?

### ISSUE THREAD

**Issue by sean-hill** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#142]
Guys, why can't you just pass me the deep link data when the `initSession` promise is resolved? Having to define a global `DeepLinkHander` function prevents me from using this plugin with an Ionic application where I'd like to wrap this plugin in an Angular service. 

Depending on a different variables (such as being logged in, or viewing a landing tutorial) I will call `Branch.initSession` in different controllers throughout my Ionic application. Having to upgrade from `1.8` to `2.0` will be very difficult and time consuming since I'll have to define this new `DeepLinkHandler` function and then try to make it talk with Angular's services / controllers. 

I want to upgrade to `2.0` because I currently have bugs with `1.8` such as the callback for the `branch.logout` function is never being invoked.

I'd appreciate it if an update could be made where the deep link data is just passed with the `res` of the `initSession` resolved promise. Thanks.

**Comment by renesansz** [comment]
Hello @sean-hill ,
I apologize if the `DeepLinkHandler` implementation gives you inconvenience to your app. In Android `initSession` is promisified. But in `iOS` initSession couldn't get the callback reference that's why you have to explicitly implement the `DeepLinkHandler` function.
See issue #128 , there's a way for `DeepLinkHandler` to be able to communicate with your Angular app.
Let me know if this resolve your issue.

**Comment by sean-hill** [comment]
@renesansz thanks for the reply :) I'll take a look.

**Comment by aaustin** [comment]
Hey @sean-hill - Sorry about this :( Here's the issue comment he's referring to: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK/issues/50#issuecomment-206113980
