### ISSUE TITLE
Sharing a url not redirecting to app in IOS

### ISSUE THREAD

**Issue by ddalmia** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#154]
Hi,

We are facing problems with Branch SDK for cordova for IOS platform. When we share the branch url on to facebook and then try opening the app from the url shared it is not happening. Instead it gets redirected to the fall back url. It works only from Twitter and native gmail app for IOS.

Facebook is not the only one even when we try to open the url from google hangout, skype, yahoo mail etc we get similar problems.

**Comment by aaustin** [comment]
Hey @ddalmia - Unfortunately, Facebook has blocked deep linking on iOS universally. If you try to open up the app, it will pop open a modal asking if you want to leave Facebook, even if the user doesn't have the app. If the user doesn't have the app, pressing 'Open' does nothing. Because of this, Branch has opted to redirect users to the fallback URL 100% of the time.

If you want to safely open up the app from Facebook, we recommend that you use our [app banner](https://dev.branch.io/features/smart-banner/overview/) on your site. Then, if the user clicks a link from Facebook and sees the page, they can click the banner and we will successfully open the app.

On the other browsers (hangouts, skype, yahoo mail), I bet they'll behave similar to Gmail and we can probably add an exclusion to treat them like so. I'm adding this to our backlog to try these others out.

**Comment by ddalmia** [comment]
Thanks for the quick reply. I will be waiting for your response on other modes i.e. hangouts, yahoo mail, Open link from SMS or whatsapp.

**Comment by aaustin** [comment]
Hey @ddalmia - I'm going to close out the issue here since this is unrelated to the repository. I've noted in our backlog that we should update the issue when it's patched (if there's a good solution for those platforms).

**Comment by aaustin** [comment]
Hey @ddalmia. Bad news. I've just tested iOS Skype, Hangouts and Yahoo Mail. All of these apps block deep linking from an initial click right now. There's no technical way to open the app when installed.

The reason being is that all of these apps intercept the clicks for their own internal analytics, before opening either the Safari app or Safari View Controller. This behavior is very similar to Facebook today. What we recommend is that you use [deepviews](https://dev.branch.io/features/deepviews/overview/) if you don't have a site and our [web to app tools[(https://dev.branch.io/features/journeys/advanced/#web-to-app-routing-without-journeys) if you don't.

We'll keep monitoring these channels to see if they make changes to their apps.
