### ISSUE TITLE
Branch.loadRewards() on cordova no results for custom bucket

### ISSUE THREAD

**Issue by chris08002** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#179]
On ionic/cordova the function loadRewards() returns an integer (number of credits in default bucket). So I can not get info on the credit in custom buckets. 

```
Branch.loadRewards().then(function (rewards) {
  console.log("rew", rewards);
  // will return the balance of the current user's credits
  $scope.credits = rewards['beer'];
}).catch(function (err) {
  console.error(err);
});
```

According to documentation it should return an array or object with the different buckets and their credit status.

This is refering to my post in stackoverflow:
http://stackoverflow.com/questions/38654869/branch-io-with-cordova-branch-loadrewards-no-results

And also to my branch.io support request.

**Comment by renesansz** [comment]
Hey @chris08002 ,
I'll take a look on the issue and hopefully provide a fix asap.

**Comment by renesansz** [comment]
@chris08002 ,
I think there's a misunderstanding w/ what the Branch.IO documentation tells about the `loadRewards` return, it doesn't return an object/array but only an **integer**.

However, I've modified `loadRewards` to accept a `string` parameter so that you can specify a bucket to load a reward.

Hopefully PR #180 caters your problem.
Let me know if this works for you. 👌

**Comment by renesansz** [comment]
@chris08002 , PR has been merged.
Is this issue now resolved?

**Comment by aaustin** [comment]
Done.
