### ISSUE TITLE
[Help] Need Clarification in Documentation

### ISSUE THREAD

**Issue by adityasaxena** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#257]
Hi Team,

Need clarification on a few things which I find missing in the documentation or are probably not clarified well. Please advise on the below:

1. Do my iOS and Android Apps need to be installed via App Store or Play Store for Branch.io links to work? 
- If so, how do I test my Test Applications? I see a step in the documentation which says, try running `cordova run android` but I don't see any steps such as signing with keystore etc. Really need to know how to test the applications without the application coming from Play Store or App Store.

2. Is a higher Node version (6.x+) necessary for this plugin to work? My AndroidManifest.xml doesn't get the full list of intent-filters with Node 0.12.7 but it does get the entire list when used with Node 6+. It's not in the documentation anywhere. I can help to add it - but please let me know this is the case.

3. Please clarify what should be the behaviour of Branch deep links in iOS versions **less than iOS 9.2 and Android less than 6.0** 

4. On one of my Apps, I pasted a Deep Link in Hangouts. When I clicked on the link, my app opened inside Hangouts itself. What could I be doing wrong here ? _**Update** As soon as I set `Android launchmode to singleInstance`, this problem went away_

thanks for your wonderful plugin! If I can help in anyway to improve documentation, I will.

**Comment by renesansz** [comment]
@adityasaxena 
1. Nope, you don't need to deploy your app to the appstore in order to test it
2. I'm not sure if Node version affects the behavior of the plugin, all of the functionality of the plugin relies on the native SDK itself
3. That I do don't know, maybe @rubinsingh has answer to this?
4. Yes, you need to set the launchmode to `singleInstance`

**Comment by adityasaxena** [comment]
@renesansz Something is not right about No.2. I have just not been able to set entitlements working properly. Can someone help me debug this please ?

**Comment by ethanneff** [comment]
Hello @adityasaxena,

1) You do not need the app to be in the App Store or Play Store to test. You can [simulate an install](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-simulating-an-install) without your app being in production.
2) The high node version is a requirement for a reason I am unfamiliar with. I can look into for you
3) For iOS below 9.2, the deep link should open the app based on URI Schemes. For Android, URI Schemes are used in all versions. Are you experiencing problems with lower OS versions?
4) You are correct, `<preference name="AndroidLaunchMode" value="singleInstance" />` has been added to the documentation.

Best,

**Comment by adityasaxena** [comment]
@ethanneff Hi Ethan, Thanks for your response. So, I'm set with 4 but others are still hazy.

1. I want to distribute my app to test users - something like an ad-hoc distribution if you will - how can they test out deep linking, do they have to follow the same steps - is there no other way to test ?
2. Please let me know if you can find out - why the higher node version is needed - could be a good addition to the documentation
3. Understood for Android. For iOS though, the Deep Link does not open up my test app even if it is installed. Is that something you have faced before or does it sound like a configuration issue ?

**Comment by ethanneff** [comment]
Hello @adityasaxena,

Again, sorry for the delay.

1) If you want to test your app to users, you can either give them the .apk for Android or send them a TestFlight link if iOS. Keep in mind, TestFlight does scramble the IDFA of the device for iOS so the metrics you get in the backend of Branch will be slightly skewed since we will not be able to accurately distinguish installs.

2) The high Node version is needed for the SDK's dependencies. We can probably build around this if needed, but as of right now, there is no timeline for this feature to be implemented. Your best bet is to build with the latest Node and Cordova version for your app.

3) If you are having trouble opening up the app for iOS, you will need to make sure you have properly integrated Universal Links for your app. You can do this by making sure:
   - Your Branch Dashboard is [properly configured](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-branch)
   - Your config.xml has the [right values](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app)
   - You have [not disabled Universal Links on your device](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios)

I am closing this ticket. Feel free to reach out if you still have questions.

Best,
