### ISSUE TITLE
Problem into showShareSheet() share with facebook

### ISSUE THREAD

**Issue by fx69005** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#263]
hi again,
i use your last commit (2.4.7) but i  have a problem now with share to facebook.
When i call my function showShareSheet() , i have the window with share possibility . 
And when i click on Facebook ( not Save to Facebook ) , the  "Save to Facebook" called . Before this update, works great

I just test on android phone, i can try to test on IOS if u want

before that , I forget delete my app and  all works fine , deeplink and button share to facebook.

Best regards

**Comment by ethanneff** [comment]
Hello @fx69005,

Can you please provide me with some screenshots? I've just tested the latest version of the Branch SDK (2.4.7) and the showShareSheet() function is working for both iOS and Android for Facebook. 

I'm not too sure what you mean by "save to facebook".

Best,

**Comment by fx69005** [comment]
Hello @ethanneff ,
so  when i click on this button

![img1](https://cloud.githubusercontent.com/assets/5602148/21247987/016e92fa-c334-11e6-9c08-fedb0907e554.jpg)

I have this message 
![img2](https://cloud.githubusercontent.com/assets/5602148/21248006/25ca3136-c334-11e6-8581-a4b117cc600b.jpg)

this message in english is : register in Facebook , only you can see the things you save.

**Comment by fx69005** [comment]
Hello @ethanneff , do u seen my screenshot ?
best,

**Comment by ethanneff** [comment]
Hello @fx69005,

Sorry about the delay. I am looking into this. I will reach out as soon as I have more information.

Best,

**Comment by ethanneff** [comment]
Hello @fx69005,

Did you make any changes to your Facebook settings, Facebook account settings, or the Facebook user on your device? The error you are getting is a [Facebook error](https://www.facebook.com/help/833282696681783) for unauthorized access. This typically happens whenever you are trying to generate a Facebook post to a place on Facebook which you do not belong to.

Best,

**Comment by fx69005** [comment]
Hello @ethanneff ,

No, i didn't change my Facebook settings. When i use "showDialog()" function by "Cordova facebookv4 plugin", le window 'Share' works great. so my facebook setting is good

But when i use showShareSheet() in your plugin. 'Save to facebook' is triggered ( green box in the picture )

![img3](https://cloud.githubusercontent.com/assets/5602148/21346661/976ec1ca-c6a5-11e6-9cb0-d30467c23bc1.jpg)

**Comment by renesansz** [comment]
@fx69005 , can you try to disable the `Cordova facebookv4 plugin` your using? This might be having a conflict with the share sheet functionality.

**Comment by fx69005** [comment]
@ethanneff , i tried but not works when i delete cordova Facebookv4 plugin on my project

**Comment by fx69005** [comment]
@ethanneff 
i try on an other an device and works great ! it works on Nexus 5 android 6.0.1
![img11](https://cloud.githubusercontent.com/assets/5602148/21361743/9fb6d2ec-c6e5-11e6-9c27-39e138e5e72c.png)
![img10](https://cloud.githubusercontent.com/assets/5602148/21361744/a13d76a2-c6e5-11e6-8e57-c91d4f221759.png)


but on my Samasung GS7 android 6.0.1  same problem. 
if u look share sheet modal u can see only ' Facebook' button on Nexus 5 but on Samsung GS7 we have 2 buttons 'Facebook' and 'Save to Facebook' .

**Comment by ethanneff** [comment]
Hello @fx69005,

Sorry about the delay. It took us awhile to get a Samsung GS7 Android 6.0.1 test device. Unfortunately, we are still unable to replicate this issue. We cannot get `Save to Facebook` to show in our ShareSheet.

- How are you getting `Save to Facebook` to show in your sharesheet?
- Is it related to the `Cordova facebookv4 plugin` you had installed?
- Have you tried deleting and re-installing the app after removing the `Cordova facebookv4 plugin`?

The reason why I ask is because no one on our team has seen `Save to Facebook`, so we are having trouble debugging your issue. Any information you can provide would be appreciated and helpful.

Best,

![screenshot_20161223-114655](https://cloud.githubusercontent.com/assets/2933593/21461401/2262d368-c906-11e6-81c3-58ec6f2c403a.png)

**Comment by fx69005** [comment]
hello @ethanneff ,
Thanks for your reply,
Cordova Facebookv4 is uninstalled and i have 'save to facebook' button. i think is an another app or something like that who create this button. Probably only on my smartphone. 

so we can close this thread.

But have do you have a date for merge  this pull request ? : #261 
I need this  because  i use "ionic package" for create my app on IOS

Merry christmas !

**Comment by ethanneff** [comment]
Hello @fx69005,

I have finally figured out your issue! When you have your device showing the `Facebook` and `Save to Facebook` options and you select the `Facebook` option, the first time, you will be presented with this screen:

![zb348xwejcqmbu1oy1ktmxxemkfitiriyw](https://cloud.githubusercontent.com/assets/2933593/21698980/71743aa8-d34e-11e6-9acb-7af8f2507f30.png)

If you select the `Share with Save to Facebook` and click `always`. Every subsequent Facebook share you make, instead of posting to your Facebook feed, will directly use the `Save to Facebook` option and save it under the Saved Tabs. Unfortunately, this is how the Facebook app is structured and there is nothing Branch can do about this.

To reset these app links, please follow the following steps:
- Go to Settings
- Select Apps
- Tap on the Gear at the top right corner
- Select App links
- Scroll down to Facebook
- Tap on clear Defaults

Doing this should show you the Above Menu again. This will allow you to make sure clicking on `Facebook` will share to `Facebook`.

Best,

**Comment by fx69005** [comment]
hello @ethanneff ,
thanks for your answer , works now!

Do you have an idea of date to merge #261 ? i really need it ! thanks

**Comment by ethanneff** [comment]
Hello again @fx69005!

Unfortunately, that pull request may take a month or two before it is merged. 
- #261 is low priority since the current Cordova Branch SDK is stable
- #261 is large update with many breaking changes
- #261 needs extensive regression tests to make sure the major release is robust

I apologize for the bad news. Branch wants to make our products the best they can be, and in doing so, we need to make sure we do not negatively impact any of our users with major releases.

Regards,
