### ISSUE TITLE
Chrome Intent error

### ISSUE THREAD

**Issue by benwilkins** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#265]
After installing the Cordova plugin and configuring Branch in the dashboard, I'm getting an error in Android. iOS works as expected.

When I visit the link, Chrome throws an error on the URL `intent://...` with `ERR_UNKNOWN_URL_SCHEME`. I've followed the install instructions best I could. I'm on Android Marshmallow 5.1.

**Comment by ethanneff** [comment]
Hello @benwilkins,

The reason why you are getting the `ERR_UNKNOWN_URL_SCHEME` could be because of the following reasons:

1) The user is being blocked by a sign-in firewall router feature
2) The user is pasting a Branch deep link into Chrome (Branch links need to be clicked on, not pasted into browser address bars)
3) The user is opening a Branch deep link within an in-app browser that is not compatible with deep linking

We currently bug filed with Google about #2 (https://bugs.chromium.org/p/chromium/issues/detail?id=638672)

To uncover what could be causing the issue with your app, can find us the steps the user did to get to this screen? A video will be nice, but steps would be okay too. 

This information will be helpful in us find a solution or providing you with a workaround.

Best,

**Comment by benwilkins** [comment]
The user is clicking on the link from an email. The email is being opened in Gmail from within the Chrome browser.

**Comment by benwilkins** [comment]
@ethanneff Any thoughts on what could be going wrong? I can reproduce the error myself. When I email the link to my Gmail account, open Gmail in the Chrome browser on my device, click the link, I get the `ERR_UNKNOWN_URL_SCHEME` error. Is this a bug in Chrome? My device is on Marshmallow.

**Comment by aaustin** [comment]
Hey @benwilkins - This is most likely an issue with the configuration of your app. Would you mind writing into integrations@branch.io with some details and the team can help you out there? Really appreciate it.

Closing this issue since it's unrelated to this repo.
