### ISSUE TITLE
Provide better API error descriptions

### ISSUE THREAD

**Issue by b12f** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#295]
Currently all 40x errors (barring 409) return the error 'The request was invalid', with no further information.

While debugging I resorted to adding `NSLog(@"Branch API error: %@", serverResponse);` to Branch-SDK/BNCServerInterface.m:129, but I'm sure a better solution to this problem can be found. Just using the message the API returns would be great.

**Comment by ethanneff** [comment]
Hello @b12f,

Do you remember the steps you did to replicate the 400 errors? Ideally, you should never be running into them when using Branch. Knowing how you got them will help me in fixing them

In the meantime, I will look into methods of passing these errors down to the Javascript level.

Thanks in advance,

**Comment by b12f** [comment]
Hi Ethan,

The error was not directly related to your code, see [this issue](https://github.com/dpa99c/cordova-custom-config/issues/106) for more information. I was basically sending "live" (or something similar, I never got to look at the sent request) as the key.

The only problem was that debugging took forever since I had no idea where to start.

Thanks for the quick response

**Comment by ethanneff** [comment]
Hello Benjamin, 

Unfortunately, doing the modification in your config.xml as in [this issue](https://github.com/dpa99c/cordova-custom-config/issues/106) will not work. It may modify the iOS pList correctly, but it will not modify the iOS Entitlements (required for Universal Links deep linking iOS 9.2+), it will not modify the AndroidManifest.xml for Android URI Schemes, and it will never switch to test mode in either iOS or Android.

The reason why we only have one branch key in the Branch Cordova SDK:
```xml
<branch-config>
  <branch-key value="key_live_ndqptlgXNE4LHqIahH1WIpbiyFlb62J3" />
```

Is because the live and test key duo configuration is rarely used. Most of our partners just omit the testing data from their analytics whenever they are doing their reporting. Additionally, the duo configuration requires changes in multiple places to work:

iOS Entitlements:
```xml
<dict>
  <key>com.apple.developer.associated-domains</key>
  <array>
    <string>applinks:cordova.app.link.app.link</string>
    <string>applinks:cordova.app.link-alternate.app.link</string>
    <string>applinks:cordova.app.link.test-app.link</string>
    <string>applinks:cordova.app.link-alternate.test-app.link</string>
  </array>
</dict>
```

iOS pList:

```xml
<key>branch_key</key>
<dict>
  <key>live_key</key>
  <string>key_live_xxxxBKA4CTHFv33Fy21YmbeiyrjdVyV8</string>
  <key>test_key</key>
  <string>key_test_xxxxBKA4CTHFv33Fy21YmbeiyrjdVyV8</string>
</dict>
```

AndroidManifest.xml
```xml
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="https" android:host="cordova.app.link" />
</intent-filter>
```

```xml
<intent-filter android:autoVerify="true">
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <data android:scheme="https" android:host="cordova.test-app.link" />
</intent-filter>
```

```xml
<meta-data android:name="io.branch.sdk.BranchKey" android:value="key_live_ehqc52LYAloHX67JtTwKYaontzdjK5JR" />
<meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_cazg9YK0AnoQ5W3RxRAQXnfosvfnLZU2" />
```

Android and iOS:
```swift
Branch.getInstance().initSession();
Branch.getTestInstance().initSession();
```

The duo live and test key configuration is more complicated than needed. Internally we normally recommend partners to stay with their live key, and use `setIdentity()` on their test accounts so they can easier filter out their data from their [Branch Dashboard](https://dashboard.branch.io/marketing).

I have added this feature request to the backlog and will discuss it with my manager. The current workaround of switch your branch key between live and test in your config.xml
```xml
<branch-config>
  <branch-key value="key_live_ndqptlgXNE4LHqIahH1WIpbiyFlb62J3" />
```

Thanks,
