### ISSUE TITLE
Twitter Share does not show preview

### ISSUE THREAD

**Issue by jvjvjv** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#305]
Hi.

I'm trying to share an app link through Facebook and Twitter. When I share via FB, the preview appears (title, preview image), but on Twitter no such preview appears. 

I've a feeling this is an SDK issue, not a plugin issue, but since I'm more familiar with Cordova/Ionic, I'm posting it here.

Will you be able to help out?

**Comment by ethanneff** [comment]
Hello,

Thank you for reaching out. 

Our Cordova SDK is built on top of our iOS SDK. I am able to get images to appear on both of our SDKs, however, it looks like the preview images are showing the Deepview instead of the image. 

- Cordova
  - <img src="http://i.imgur.com/xa0qEDo.jpg" width="200">
- iOS 
  - <img src="http://i.imgur.com/aBl0hvp.jpg" width="200">

**Comment by jvjvjv** [comment]
Thanks, @ethanneff. Would (website to app routing)[https://dev.branch.io/features/website-to-app-routing/] accomplish the same thing, since a we'd prefer to link to our existing website?

**Comment by ethanneff** [comment]
Hello again,

The [website to app routing](https://dev.branch.io/features/website-to-app-routing/) is used to transform web users to app users. Instead of viewing your content on a mobile browser like Safari, this feature will drive users to view your content insides your app.

On the other hand, the [in-app sharesheet](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#share-deep-link) is used to share your links. This will popularize your app content and drive users into your app.

Both features work with one another to grow your app.

P.S. I talked to my iOS engineer and apparently the [deepview](https://dashboard.branch.io/settings/deepviews) is the only workaround for your Twitter share sheet issue. This is a limitation of the way Twitter scrapes the image link and not a limitation of Branch.

Best,

**Comment by jvjvjv** [comment]
Thanks. This is very helpful. I've passed the response over to another member of my team, involved in dev. Is the use of your in-app sharesheet recommended over using , say, [another social sharing plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin)?

**Comment by ethanneff** [comment]
Hello again,

Apple is restrictive in the way they let users share content between apps. For iOS, you can only use the `UIActivityView​Controller`. [Apple Docs](https://developer.apple.com/reference/uikit/uiactivityviewcontroller). 

Both the [Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#share-deep-link) and the [Social Sharing Plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin) use the `UIActivity​View​Controller`. 

I am not an expert in the [Social Sharing Plugin](https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin), so there is a chance it may have more capabilities than the [Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#share-deep-link) in the way they leverage the `UIActivity​View​Controller`. I have a feeling the differences will not be significant. Feel free to research and determine which solution better suits your app needs.

Best,

**Comment by jvjvjv** [comment]
I had figured as much.

If you disable Deepviews, and try to share via Twitter, does the preview box then become a blank white box? I'm asking to see if you can reproduce my issue on your end.

**Comment by ethanneff** [comment]
Hello again,

- Twitter scrapes the `<meta name="twitter:image:src" content="http://www.lorempixel.com/400/400/">` tag of the URL.
- The `meta` is set whenever you set `$og_image_url` of your deep link ([docs](https://dev.branch.io/getting-started/configuring-links/guide/#open-graph-tags)). 
- The `$og_image_url` is set by the `contentImageUrl` within our Branch Cordova SDK ([docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#create-content-reference)). 

You want to make sure you have `contentImageUrl` set as well as [deepviews](https://dashboard.branch.io/settings/deepviews) enabled.

I am unable to reproduce the issue of a blank white box on my end. If you are still having issues, providing me with an example deep link and screenshots will help me troubleshoot your issue. 

Best,
