### ISSUE TITLE
Documentation the README steps could include the part where we turn on Associated domains

### ISSUE THREAD

**Issue by epetre** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#313]
<img width="633" alt="associated domains" src="https://cloud.githubusercontent.com/assets/1010282/24634763/8e90e0de-189d-11e7-8a20-64c6c55b385d.png">

**Comment by ethanneff** [comment]
Hello,

I apologize, this should have happened automatically on `cordova build ios`  ([1](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/plugin.template.xml#L52) -> [2](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/scripts/hooks/afterPrepare.js#L26) -> [3](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/scripts/ios/enableEntitlements.js)). Since it didn't, I was wondering if you could provide some more information so we can fix this.
- What Xcode version are you using?
- What platform are you using? (cordova, phonegap, ionic1, ionic2, etc)
- What cordova and node version are you using? (`cordova info`)
- Do you have any plugins which might have interfered with ours?

Thanks in advance,

**Comment by epetre** [comment]
Hi, well since I added it manually, it doesn't disappear, but here is my config.
The value I used in that field was `applinks:hidden_subdomain.app.link`  I'm not sure if that's correct I took example on [this link](https://blog.branch.io/how-to-setup-universal-links-to-deep-link-on-apple-ios-9/).

**Also here is my env:**
Cordova CLI: 6.4.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: 1.9.1
ios-sim version: 5.0.8
OS: macOS Sierra
Node Version: v4.4.3
Xcode version: Xcode 8.2.1 Build version 8C1002

**Comment by ethanneff** [comment]
Hello again,

There is nothing abnormal about your configuration. The Cordova Branch SDK is setup in a way that you should never touch Xcode or Android Studio. The [settings](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app) you add in your `config.xml` should do all the configuration and native code logic for you. 

Thank you for environment information. I will investigate it and see what I can come up with.

Thanks,

**Comment by ethanneff** [comment]
Hello again,

After multiple test apps, I am still unable to replicate the issue you were having. I will monitor the issues over the next couple of months to see if this problem comes up again. 

I am glad you were finally able to get it fix, and I apologize for integration issues you had.

Best,
