### ISSUE TITLE
Branch.initSession bugged

### ISSUE THREAD

**Issue by alejandromagnorsky** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#324]
I've been trying to use this snippet on angular.run():
```javascript
$ionicPlatform.ready(function() {
    var callback = function() {
        console.log(JSON.stringify(Branch));
        Branch.initSession(function(data) {
            // read deep link data on click
            console.log('Deep Link Data: ' + JSON.stringify(data));
        });
    };
    $ionicPlatform.on('deviceready', callback);
    $ionicPlatform.on('resume', callback);
});
```

But all I get in the console is:
```javascript
{"debugMode":false}
Deep Link Data: {"+is_first_session":false,"+clicked_branch_link":false,"+non_branch_link":"spurrewards://open"}
```

I'm using an Android 7.0.1 phone and the link x.app.link opens the app but I can't do further deep-linking without the data (by redirecting to the specific URL inside the app).

Also, this is my cordova info:
```
Node version: v7.10.0

Cordova version: 6.5.0

Plugins: 

branch-cordova-sdk,com.muulla.location,cordova-plugin-compat,cordova-plugin-console,cordova-plugin-crosswalk-webview,cordova-plugin-dialogs,cordova-plugin-geolocation,cordova-plugin-google-analytics,cordova-plugin-inappbrowser,cordova-plugin-splashscreen,cordova-plugin-statusbar,cordova-plugin-whitelist,cordova-plugin-x-socialsharing,cordova-plugin-x-toast,cordova.plugins.diagnostic,es6-promise-plugin,ionic-plugin-keyboard,onesignal-cordova-plugin

Android platform:

Available Android targets:
----------
id: 1 or "android-25"
     Name: Android 7.1.1
     Type: Platform
     API level: 25
     Revision: 3
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.

iOS platform:

Xcode 8.3.2
Build version 8E2002
```

**Comment by alejandromagnorsky** [comment]
I'm not sure if this is the reason but after doing some testing it seems that with HTTPS (https://my.app.link) it works.

**Comment by ethanneff** [comment]
Hello,

Can you please provide me with some more information on how you are testing? I have a feeling data is not passing through because you are clicking on `spurrewards://open` which is not a deep link. `spurrewards://open` is a URI Scheme. URI Schemes will open your app, but they will not pass data (you will have to manually parse the `open` from `+non_branch_link`). 

If you want to pass data into your app and track analytics of your clicks, installs, opens, and users, then I would recommend using Branch deep links instead (for example `https://cluv.app.link/6TOiVlCqXx`). Theses URLs are smart with redirects, custom data, and analytics. Using HTTP or HTTPS will not make a difference with them.

Furthermore, I would not recommend the following code as you are overriding all `$ionicPlatform.on('deviceready'` and all `$ionicPlatform.on('resume'` listeners with one `callback` function. 
```js
    var callback = function() {
        console.log(JSON.stringify(Branch));
        Branch.initSession(function(data) {
            // read deep link data on click
            console.log('Deep Link Data: ' + JSON.stringify(data));
        });
    };
    $ionicPlatform.on('deviceready', callback);
    $ionicPlatform.on('resume', callback);
```

Separating these listeners into separate functions, as demonstrated [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#initialize-branch), will save you some headache in the future. 

Thanks,

**Comment by alejandromagnorsky** [comment]
Hi, 
Regarding the issue, I was not using URI Scheme (even though it logged that). 
I was always using Universal links (or Branch deep links). And as I said before, it works now, so not sure what happened at the beginning (I think it was HTTP vs HTTPS but you mention that indistinct).

Feel free to close this ticket.

**Comment by ethanneff** [comment]
Feel free to reach out if you ever have any more issues.
