### ISSUE TITLE
Instead of opening application directly, Branch.io takes me to the App Store

### ISSUE THREAD

**Issue by razam217** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#327]
Hi, I've been using branch.io for almost 2 years. There was a requirement from client that the app should directly open instead of taking the user to the App Store.
I updated the plugin and Android started working. But IOS do not.

In xcode I can see all the configurations in my info.plist. Also I have configured everything in the branch dashboard.

Note: I'm using branch.io old url i.e. bnc.lt.

**Comment by ethanneff** [comment]
Hello,

Unfortunately, the `bnc.lt` link domain has been and will continue to be fazed out. It is a legacy link domain which has been replaced by `app.link`. There is a good chance that your AASA entry for `bnc.lt` has been removed which will break your app's ability to deep link directly into the app using Universal Linking. Branch has emailed all of our partners last year regarding this change. I apologize for any inconvenience it has caused.

The good news is you can switch to an `app.link` link domain on your [Branch Dashboard](https://dashboard.branch.io/link-settings). Whenever you [configure](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-optional-app-config) you `config.xml` for Branch, you will need to include both your new `app.link` link domain as wells as your `bnc.lt` link domain.

Thanks,

**Comment by razam217** [comment]
Thanks @ethanneff. 
I'm confused about one thing, if I change my link domain from bnc.lt to app.link, will this break all my existing links that are based on bnc.lt? My application is already published on app store, and we've many customers who are using this. 

What will happen if:
- I change my link domain from bnc.lt to ___app.link
- I update the cordova plugin to the latest version and also update its code accordingly

**Comment by ethanneff** [comment]
Hello again,

Since your `URI Scheme` is not changing in your migration from `bnc.lt` to `app.link`, your old links will continue to work. Depending on how you created the `bnc.lt` links, they might navigate to your fallback_url or default_url you have set on your [Branch Dashboard](https://dashboard.branch.io/link-settings). The good news is as soon as the user opens the app, then the deep link data will pass through. 

Besides switching to `app.link`, you will also need to [update your Branch SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) as well. This will enable Universal Linking for your app (clicking will open the app directly instead of first redirecting to a browser).

I would recommend the following:
1) [update](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) your Branch SDK
2)  [configure](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-optional-app-config) your `config.xml` for Branch to include both `bnc.lt` and `app.link`
4) [switch] to `app.link`on your Branch Dashboard (https://dashboard.branch.io/link-settings)
5) [test](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-ios) universal linking with an `app.link` from your [Branch Dashboard](https://dashboard.branch.io/quick-links)
6) submit your app to the App Store/Google Play Store
7) create `app.link` links for all your new campaigns on the [Branch Dashboard](https://dashboard.branch.io/quick-links)

Thanks,

**Comment by razam217** [comment]
So this means the data will still pass through using bnc.lt domain after switching to app.link domain and will also take me to the app store (my app page). I'll get back to you soon once I'm done with it tomorrow.
Thanks a lot @ethanneff...

**Comment by razam217** [comment]
Hi,

@ethanneff when I tried to switch to .app.link domain, it warned me that the links created with bnc.lt domain, will no longer work. Please see the attached image. 

Thanks


![screen shot 2017-05-25 at 11 20 19 am](https://cloud.githubusercontent.com/assets/9858462/26438471/9fca78ac-413c-11e7-823a-9c03554c5526.png)

**Comment by ethanneff** [comment]
Hello again,

I have just spoken with my infra team and this error message on the dashboard is incorrect. Your old `bnc.lt` links will continue to navigate to (URI Scheme) and pass data into your app (Deferred Deep Linking).

I am not too sure if you will be able to change from `bnc.lt` to `app.link` on the dashboard due to some UI constraints (related to the incorrect dashboard error message). If this is the case, can you please email support@branch.io with your Branch Key (https://dashboard.branch.io/account-settings/app) and the `app.link` link domain you want to change to? We will make the migration for you.

Thanks,

**Comment by razam217** [comment]
Nice. I'll try to change from _bnc.lt_ to _app.link_, if it does not allow me to change, I'll email at support email address. 
Should I mention something related to my problem in that email or only the branch_key is sufficient?
I'll try it in the morning and will get back to you on this. 

Thanks,

**Comment by razam217** [comment]
Hello @ethanneff ,

As you mentioned that I will not be able to change the link domain, so when I tried it wasn't really changing. I emailed at support email address, and they updated.

Now the serious problem with me is my links with new domain and old domain, both are not working on old android application which is already published on play store. Its critical, please let me know what I'm missing? 

Although they are taking me to the app store, but when I open my application, it do not pass data.

Thanks,

**Comment by razam217** [comment]
Branch.io API is returning 400 error with this response:
{
  "error": {
    "has_nfc": "wrong field type",
    "screen_height": "wrong field type",
    "has_telephone": "wrong field type",
    "screen_width": "wrong field type",
    "screen_dpi": "wrong field type",
    "bluetooth": "wrong field type",
    "update": "not a valid option"
  }
}
Please also have a look at attached image.
<img width="1068" alt="screen shot 2017-05-27 at 7 08 25 am" src="https://cloud.githubusercontent.com/assets/9858462/26517164/56392050-42ac-11e7-8aa7-b83998291cd7.png">

**Comment by razam217** [comment]
Hi @ethanneff ,

Thanks for your support and help. My both old and new link domains are now working absolutely fine as you told me.
Thanks
