### ISSUE TITLE
Branch.initSession seems to execute too early

### ISSUE THREAD

**Issue by Mikechaos** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#338]
Hi all,

I'm having a weird problem with Branch.initSession.

I have more or less the typical init you would expect
```javascript
angular.module('sfmobileApp').run(function($rootScope, configService) {
  var branchInit = function() {
    // Branch initialization
    Branch.initSession(function(data) {
      // read deep link data on click
      alert('Deep Link Data: ' + JSON.stringify(data));
    });
  };

  $(document).on('deviceready ready', function() {
    branchInit();
  });
  $(document).on('resume', function() {
    branchInit();
  });
});
```

When the app is closed, the app take the time to initialize and I get the expected behavior. After the splash screen is shown the appropriate destination screen and everything is for the best!

But if I click on the same deeplink but the app is already open, I seem to get a race condition. I know it's a race condition because if I stick a breakpoint or a setTimeout in branchInit, it magically works again.

Here's the data in the usual scenario, when the app is open (meaning 'resume' is called).
```json
{
  "+clicked_branch_link": false,
  "+is_first_session": false,
  "+non_branch_link": "salesfloor:///store-requests/id/contact_me_1993?link_click_id=396389387226696381"
}
```

And the data once it is working (same deeplink, again, but with a breakpoint or a setTimeout)
```json
{
  "$3p": "e_sg",
  "$android_url": "https://saks-stg.salesfloor.net/mobileapp",
  "$deeplink_path": "/store-requests/id/contact_me_1993",
  "$desktop_url": "https://saks-stg.salesfloor.net/backoffice/store-request-center#/storeRequests/unresolved/thread/contact_me_1993",
  "$ios_has_app_url": "https://saks-stg.salesfloor.net/ios_deeplink_fallback/ios_fallback.html",
  "$ios_url": "https://saks-stg.salesfloor.net/mobileapp",
  "$one_time_use": false,
  "+click_timestamp": 1498062693,
  "+clicked_branch_link": true,
  "+is_first_session": false,
  "+match_guaranteed": true,
  "~creation_source": 6,
  "~id": "393478711573415689",
  "~referring_link": "https://0103.test-app.link/tVpVhxDieD?$desktop_url=https%3A%2F%2Fsaks-stg.salesfloor.net%2Fbackoffice%2Fstore-request-center%23%2FstoreReque…"
}
```

Any idea why 'resume' would fire so quick Branch wouldn't be ready?
We are trying to push this to production and I've been battling for the past two days on this one. I am that close of releasing it with a setTimeout and call it a day! But I'd definitely prefer understanding what is going on :)

Thanks for the help!
Mike

**Comment by Mikechaos** [comment]
Hi again!

Fixing the issue with a `setTimeout` surfaced another issue.
Everything subsequent call to Branch.initSession (on 'resume' events for example) triggers the initial deep link click again.
I can store the timestamp of the last click and prevent the handler from firing if the timestamp are equal (they are until I actually click on a new deep link). But I'm wondering what are causing all these edge case issues and the necessity for these small hacks (`setTimeout`, store the timestamp, etc.)

We are running an Angular 1 application on Cordova 6.5.0.

Thank for your help and time!
Mike

**Comment by ethanneff** [comment]
Hello Mike,

Thank you for reaching out. 

Ideally, you should not rely on a `setTimeout()` to get deep link data through `Branch.initSession()`. Data should flow in naturally. I have a feeling there might be some misconfigurations within your app which could be causing the problem. 

When looking at your code snippet, it looks like you are using both jQuery as well as Angular 1. From experience, these frameworks do not communicate well with each other. You should be able to do everything within Angular 1 without needing jQuery. (maybe importing lodash or underscore if you need the extra methods). 

Additionally, you are calling `$(document).on('deviceready ready', function() {})` instead of `document.addEventListener('deviceready', this.onDeviceReady, false);`. This could be causing some issues with your app not recognizing the Cordova event `deviceready`. 

Finally, if you could provide me with your testing steps, I can try to replicate the issue on my end.

Thanks,

**Comment by ethanneff** [comment]
There have been no other reports of problems in over a month. Safe to assume the problem has been resolved. Closing this ticket.
