### ISSUE TITLE
Branch io not working in my android device

### ISSUE THREAD

**Issue by aashishvyas** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#360]
On click of deep link the event registered on portal but instead of opening the app it opens my default page link

**Comment by aashishvyas** [comment]
Now its working but as mention we have to paste deep link in google hangout but how to do same using any browser?
please suggest

**Comment by ethanneff** [comment]
Hello,

To make sure your deep links open your app, please make sure:
1. Your [Branch settings](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-branch) match you [app settings](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#configure-app)
1. Make sure your deep links are being `clicked` on. Copy and pasting a link in the address bar will not work because most browsers cache URLs.
1. Make sure you are not getting any [console errors](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-show-console-logs)
1. Make sure you are clicking on a `deep link` and not your link domain. Best way to guarantee this is by going through our [testing guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#test-deep-link-android)

Thanks,

**Comment by aashishvyas** [comment]
If I paste my deep link into Google hangout as mention in plugin description it opens my app but if I try same with Google chrome browser then it opens the else part(meas the scenario in which my app is not installed in device)

**Comment by ethanneff** [comment]
Hello again,

Make sure your deep links are being `clicked` on. Copy and pasting a link in the address bar of the Google chrome browser will not work because most browsers cache URLs which prevent the deep linking into your app.

Thanks,

**Comment by aashishvyas** [comment]
Hello,
I haven't copy & paste deep link in browser but still  it doesn't open application. This issue is in all phn browser including chrome, Firefox ,opera etc

In msg app like hangout, whatsapp its working fine

**Comment by ethanneff** [comment]
Hello again,

Make sure your deep links are being `clicked on`. Copy and pasting a link in the address bar of the Chrome, Firefox, Safari, or Opera will not work because the browsers will cache the URLs which prevent the deep linking into your app.

Thanks,
