### ISSUE TITLE
Handle Non-Branch Deep links

### ISSUE THREAD

**Issue by srkgupta** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#368]
I am trying to use the Firebase Login with Redirect and Firebase requires Cordova Universal Links plugin. Since this plugin is incompatible with Cordova Universal Links plugin, I am unable to use the Firebase authentication features. 

I am using the tutorial shown here, which integrates with Universal Links Plugin. 
https://firebase.google.com/docs/auth/web/cordova

How can we do the same through Branch Deep Link Plugin?

FYI, when a redirect happens after login from Facebook/Google/Twitter to the app, the Branch initSession is called with an nonBranchLink Error. Is there some way we can override this and handle?

Any suggestions would be of great help.

**Comment by ethanneff** [comment]
Hello,

As of right now, the Branch SDK does not support the Universal Links plugin as the two SDKs keep overriding each other's entitlements ([docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-incompatible-plugins)). I have tried making them compatible with one another in the past without luck. 

However, since this issue came up again, I will take another swing at it. I'll add this issue as a feature request in our backlog.

Thanks,
