### ISSUE TITLE
Error: BRANCH SDK: Invalid "android-prefix" in <branch-config> in your config.xml

### ISSUE THREAD

**Issue by SeVeNDuS** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#369]
I get this error when executing cordova build android but I don't have that tag in my config.xml

branch-cordova-sdk 2.6.12

Something is wrong in that version

Regards

**Comment by ethanneff** [comment]
Hello,

This error is generated from [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/scripts/npm/processConfigXml.js#L195). An example of a correct `android-prefix` is found [here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#testing-optional-app-config). Keep in mind, this value is only needed if you are using a bnc.lt or custom `link-domain` (non app.link link).

Can you give me an example of your `branch-config` within your `config.xml` so I can troubleshoot your issue further?

Thanks,

**Comment by SeVeNDuS** [comment]
Thanks for the quick reply

I use custom domains then the error is produced by that anyway, Which value should I put in Android-prefix??

**Comment by ethanneff** [comment]
I understand how this can be hard to find (even I am having a difficult time finding it on our dashboard). 

Your best bet is to create a link with your `branch_key` using our API (this is a cURL command you can copy-paste into your terminal).
```
curl -XPOST https://api.branch.io/v1/url -d '{
  "branch_key": "key_live_piAfzOlymTsKZwXUHo6utjilBrimGZRa",
  "channel": "test"
}'
```

```
{"url":"http://link.eneff.io/LVeu/LEa08QkyAG"}
```

The android-prefix in this example response is `/LVeu`. You need to add this to your `config.xml`.

Thanks,

**Comment by ethanneff** [comment]
Found it. If you have a custom link domain enabled, then you can find your `android-prefix` on https://branch.dashboard.branch.io/link-settings 
<img width="1328" alt="screen shot 2017-09-20 at 12 21 26 am" src="https://user-images.githubusercontent.com/2933593/30631630-ba087412-9d99-11e7-9eea-10b28c9d416b.png">

Best,

**Comment by SeVeNDuS** [comment]
Thanks!! Solved!!

**Comment by sirpy** [comment]
The above description doesnt seem valid anymore.
We are trying to configure our own domain as the applink on android, so when clicking on a link to our domain the app will open. How do we achieve that?

**Comment by ethanneff** [comment]
Custom link domains can be configured here: https://docs.branch.io/pages/dashboard/integrate/#change-link-domain

Custom link domains will have a pathPrefix attached to them (e.g. `/LVeu`) which will need to be added to your `config.xml` configuration. https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#optional-app-config

**Comment by sirpy** [comment]
I guess my question is not how to use custom domains but how do i get
regular web links to our website to open the app itself, on ios we can
easily add an applink domain and it works together with branch app.link
domain but how do we do that on android?

**Comment by ethanneff** [comment]
@sirpy The [default behavior of Branch](https://docs.branch.io/pages/links/integrate/#default-link-behavior) is:

- Your app is not installed
    - User `clicks` on a Branch deep link
    - Device `navigates` to the [fallback](#fallback-to-a-specific-url) (e.g. an app store or website)
    - User `installs` and `opens` app
    - Branch passes deep link `data` into app
- Your app is installed
    -  User `clicks` on a Branch deep link
    -  Device `opens` app
    -  Branch passes deep link `data` into app

This behavior should work regardless of Android or iOS. Of course, this behavior only works for your Branch links (deep links). Your regular web links on your website (hyperlinks) will not be able to open your app. This is because Branch deep links have thousands of unique redirections built into them. For example:  
- If Branch deep link + clicked on Facebook mobile app + clicked on Android M or greater + your app is installed, then open your app with your URI Scheme your_custom_uri_scheme://open?link_click_id=link-44270354495348291

Since converting all your web links to Branch links may be a daunting task, you can always integrate our [Web SDK](https://branch.io/journeys/) to add a banner to your website to convert web users to app users.

Thanks,

**Comment by sirpy** [comment]
it's not the question.
in other deeplink plugins such as universal-links plugin for cordova you define YOUR OWN domain as an applink domain. so any click on a link of your domain will open the app if it is installed.
so for us "knil.co", we want every click on knil.co to open the app if it is installed.
now since you say branch is not compatible with universal links plugin we need some other way to configure android (on cordova) to open links of "knil.co" in our app.

for IOS on cordova we simply add "knil.co" to the applink domains list where we add "X.applink.link"(ie branch domain) and they both work, clicking on knil.co links on ios opens our app. clicking on applink.link opens our app also with branch sdk trigger.

HOW DO WE DO THIS FOR ANDROID?

**Comment by scottwb** [comment]
Branch seems to no longer put prefixes on our links, and the dashboard UI @ethanneff shows above no longer includes an indication of what your prefix should be. Same with the curl command he gives.

However, the code still requires that you have an `android-prefix`, and it has to match a specific regex, so it cannot be blank. If you put in a fake one that that satisfies the regex, you can build, but your links won't work as App Links on Android. _This seems like a bug in https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/495e6c74134fb22e9cb479a9a372f60794b1ab87/src/scripts/android/updateAndroidManifest.js#L287 to me._ Should at least let it be optional, I think.

Anyway...if you have this problem like I do, when using custom domains with Ionic, here is my remedy:

1. Add a fake 4-letter android-prefix value to your `<branch-config>` like this:

    ```
    <android-prefix value="/Fooo"/>
    ```

2.  Make sure you have the `cordova-custom-config` plugin installed in your project.

3. Add `xmlns:android="http://schemas.android.com/apk/res/android"` to the `<widget>` tag at the top of `config.xml` for your app.

4. Add add a block like this inside the `<platform name="android">` block of your app's `config.xml`

    ```
    <custom-config-file target="AndroidManifest.xml" parent="./application/activity[@android:name='MainActivity']/intent-filter[@android:name='io.branch.sdk.AppLink']">
        <data android:host="my.customdomain.com" android:scheme="https" />
    </custom-config-file>
    ```

5. If you are using an older version of the `custom-config-file` plugin, change `<custom-config-file>` to just `<config-file>`

6. Rebuild and keep your fingers crossed. Check `platform/android/AndroidManifest.xml` to see if it looks like you want it to...that is... _without_ a prefix attribute in the `<data>` element we overwrote in step 4. (That's really all this does...replace the faulty element the branch plugin generates with your fake prefix that you don't need.)

**Comment by ethanneff** [comment]
You are correct. Prefixes are no longer needed for custom link domains (they were unsightly). I'll push a hotfix today to remove the requirement for prefixes on custom link domains
