### ISSUE TITLE
android-prefix using custom deepview

### ISSUE THREAD

**Issue by ainth** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#371]
Our app implements 'landing pages' using branch's deepview in the web sdk. These are located at eg `https://myapp.com/foo/{thing_id}`. We want only urls that look like `/foo/thing` to use universal links/app links because other urls for our product should remain web-only. For apple we're configuring the apple-app-site-association file to only handle `/foo/*` but for android it looks like we need to configure this via `android-prefix`. The regex fails when we enter `/foo` as the prefix because of the regex here: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/14256589c44376533a9d3e706557e2d78d1c5c54/src/scripts/npm/processConfigXml.js#L195.

Is forking and changing the regex here the best solution? Additionally: would the prefix cause issues with branch links and is there any way around that? ie `https://myapp.com/foo/{thing_id}` has a button that calls `branch.deepviewcta()` and ideally navigating to the branch link should trigger app link behaviour but if the prefix is set to `/foo` I assume it wouldn't..

**Comment by ethanneff** [comment]
Hello,

Unfortunately, Branch deep links do not support multiple forward slashes at the moment (e.g. `/foo/thing`).

- works https://example.app.link/4KX5DWgQEG
- works https://example.app.link/foo
- fails https://example.app.link/foo/thing

This is a limitation of our backend which we plan on addressing before the year's end. `android-prefix` will not solve the goal you are trying to achieve as this property is used to differentiate apps using custom link domains (e.eg non app.link domains). 

Since it will take awhile before the backend issues are fixed, your best bet is to create Branch deep links in one of the following ways:
- create with a random hash with `foo=thing` in the data https://example.app.link/4KX5DWgQEG
- create with a custom `alias` https://example.app.link/foo-thing
- create with a query string https://example.app.link/?foo=thing

Hope this helps!
