### ISSUE TITLE
Branch Links Cutoff in iMessage

### ISSUE THREAD

**Issue by thielCole** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#374]
When generating a branch link we dynamically create the link based on a specific item people are trying to find.

```
    Branch.createBranchUniversalObject(props).then((res) => {
        branchUniversalObj = res;

        let props = {
          $deeplink_path: '/app/challenge/' + this.challenge._id
        };

        let analytics = {
          channel: 'in_app',
          feature: 'invite_challenge',
          campaign: 'in_app'
        };

        let message = '<insert message>';

        branchUniversalObj.showShareSheet(analytics, props, message);
      }).catch(function (err) {
        console.log('Universal Error: ' + JSON.stringify(err));
        // alert('Universal Object Error: ' + JSON.stringify(err))
      });
```
But when someone tries to share this with iMessage, the link gets cutoff

![cutoff-link](https://user-images.githubusercontent.com/7246257/30945543-b9bcf7ce-a3b3-11e7-8918-2765143191c8.jpg)

link looks like https://38plank.app.link/qifygS7kN (not an actual link)
Not sure what is causing iMessage to recognize the link oddly.

**Comment by ethanneff** [comment]
Hello,

Thank you for reaching out. This is a known bug with our underlying iOS SDK for deep links which are copy-pasted into iMessage on iOS 11. The current workaround is for users to use [sharesheet method](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#share-deep-link) to share links to iMessage instead of copy-paste.

This bug has been identified, fixed, and is currently in QA. I will update the Branch Cordova SDK and update you once it is live.

In the meantime, I apologize for this inconvenience.

**Comment by ethanneff** [comment]
Hello again,

I have just updated the Branch Cordova SDK to use the latest underlying Branch iOS SDK. I would recommend updating to the latest version `2.6.14`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update your Cordova Branch SDK.

Thanks,

**Comment by thielCole** [comment]
Thanks @ethanneff . Will be updating today and testing.
