### ISSUE TITLE
Unable to get working with phonegap build

### ISSUE THREAD

**Issue by FabPey** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#386]
Hi there - very interested in getting this working. However I have been unable to get going with our phonegap app - I have followed the instructions to the letter, but when clicking the link it just goes to our default URL, it doesn't open the app. We're using side loaded apps on real devices to test this, as we're using phonegap build. Is Phonegap Build supported? I have tried Android 7.0.1 and iOS 10.3.3 and neither works.

Thanks

**Comment by ethanneff** [comment]
Thanks for reaching out!

Unfortunately, PhoneGap Build is not compatible with the Branch Cordova SDK ([docs](https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#incompatibilities)).

PhoneGap Build prevents Cordova plugin hooks (https://github.com/phonegap/build/issues/425#issuecomment-93126212). Instead of allowing Cordova to inject code, PhoneGap Build creates the apps (.ipa and .apk) from the PhoneGap servers. They do this to prevent the need of Xcode and Android Studio. However, this process bypasses the normal operations of `cordova build ios && cordova run ios` which the Branch Cordova SDK depends on. We need these operations because they call our Cordova hooks to inject deep linking functionality into the `info.plist` and `AndroidManifest.xml` of your apps. Since PhoneGap Build prevents our injections, we cannot enable Entitlements, Universal Linking, URI Schemes, and App Links. 

If you are still interested in using the Branch Cordova SDK, the PhoneGap CLI is still supported by us.

Thanks,

**Comment by valentinvoilean** [comment]
Can someone please update the repository name to avoid any confusion related to phonegap ?
