### ISSUE TITLE
ios - Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<BranchUniversalObject 0x1c42ece80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key integer.'

### ISSUE THREAD

**Issue by mkwsra** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#390]
I'm sorry for the long title.

I'm facing this error for a very long time, and I could not find any reasonable explanation on the internet so I'm posting it here!

I have this problem on iOS only

<img width="750" alt="screen shot 2017-11-09 at 10 27 40 pm" src="https://user-images.githubusercontent.com/1743919/32625521-73a6639a-c59d-11e7-987b-6c87809e0982.png">

**Comment by ethanneff** [comment]
Hello Hello!

So the `Branch Universal Object` is created by this method ([docs](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#create-content-reference))
```js
// only canonicalIdentifier is required
var properties = {
  canonicalIdentifier: 'content/123',
  canonicalUrl: 'https://example.com/content/123',
  title: 'Content 123 Title',
  contentDescription: 'Content 123 Description ' + Date.now(),
  contentImageUrl: 'http://lorempixel.com/400/400/',
  price: 12.12,
  currency: 'GBD',
  contentIndexingMode: 'private',
  contentMetadata: {
    custom: 'data',
    testing: 123,
    this_is: true
  }
}

// create a branchUniversalObj variable to reference with other Branch methods
var branchUniversalObj = null
Branch.createBranchUniversalObject(properties).then(function (res) {
  branchUniversalObj = res
  alert('Response: ' + JSON.stringify(res))
}).catch(function (err) {
  alert('Error: ' + JSON.stringify(err))
})
```

It looks like you are getting an `NSUnknownKeyException` error. I have a feeling this could be caused by malformed JSON, or by an invalid key-value pair passed into this method. 

Can you try the example above to see if you still get the same error? Furthermore, it would be helpful to get an example of your code and the data you are passing so I can troubleshoot it on my end.

Thanks,

**Comment by mkwsra** [comment]
Thank you so much for your help, it was my fault, I was trying to add more details into the object that I'm passing into `Branch.createBranchUniversalObject(HERE_IS_THE_OBJECT_I"m_PASSING)`

Thank you so much, when I removed it, everything worked just fine, and I was wondering why I can't add more details other than the known ones! and obviously it's my bad
