### ISSUE TITLE
Branch.initSession not return data when opened link in app

### ISSUE THREAD

**Issue by YaroslavG** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#394]
Hi everybody,
DeepLink works perfect, but when I try open this link in my app, I get not anything in Branch.initSession, it works only if I open this link in browser,
any ideas?
I add a screenshot below
![0-weu-d2-9808baa3a43aace4e3b3aa3a963fdf35](https://user-images.githubusercontent.com/5793103/32836116-6aeed3d6-ca11-11e7-821c-6eda3d0e1e99.jpg)

**Comment by ethanneff** [comment]
Hello!

This problem may be related to how the app and the device behave. The app sees the Branch deep link in your app and thinks of it as a URL - which triggers the default browser (iOS = Safari, Android = user choice) to open. This makes the user leave the app to the deep link's fallback. Unfortunately, the deep link is unable to enter back into the app because of [restrictions from the device](https://blog.branch.io/the-problem-with-safari-app-redirects/). This leaves the user outside of the app, and without deep link data. 

I can test around see if there is any feature can do send deep link data back into the app, however, I have a feeling this problem is the resultant of the app and device which is outside of Branch's control.

I'll still investigate to see what I can find.

**Comment by dbek** [comment]
Hi @ethanneff !
I'm working with @YaroslavG on this issue. The thing is, the link doesn't open in a browser, it is consumed by the app (this is easier to see on Android with the "open in app" option), so the user stays inside the app, but Branch.initSession doesn't catch the event of a deeplink being clicked.

**Comment by Coolcat13** [comment]
hi @ethanneff & @YaroslavG - any update on this issue? It is a major headache for us. Thanks in advance

**Comment by dbek** [comment]
Hi, @Coolcat13 ! No solution yet, we're currently using a workaround with a custom payload included in branch link, but we definitely want to find the root of the issue.

**Comment by Coolcat13** [comment]
@dbek thanks, would you be able to share the details of your workaround?

Thanks in advance

**Comment by dbek** [comment]
@Coolcat13 pretty simple - [deeplinks](https://docs.branch.io/pages/links/integrate/#short-links) may have additional parameters added, we are using a template like this:
https://example.app.link/fzmLEhobLD?__parameter=value
and a custom uri listener, that is looking for a __parameter in a deeplink. And instead of opening a link - we parse out the payload and do whatever action is needed :)
So the same deeplink outside the app don't have attached parameters, and an in-app distributed one has added parameters.

**Comment by ethanneff** [comment]
Hello everyone,

Thank you for your patience. 

Bad news: in-app deep linking (clicking on a Branch deep link within your own app to retrieve deep link data) is not supported. I have tried numerous workarounds to get this functionality working, but it seems this scenario is outside of Branch's control. Below are some of my findings:

Firstly, in-app deep linking is not supported by our native SDKs (iOS and Android) which the Branch Cordova SDK depends on. When simulating an in-app deep link on iOS with `UIApplication.shared.openURL(URL(string: "https://link.eneff.com/LVeu/3sSshbx17H")!)`, similar results happened. The app ejects to Safari and no deep link data is passed to the app.

Additionally, in-app deep linking has a different experience depending on the device's operating system. On iOS, the user is ejected to Safari. On Android, the user is maintained in the app. Deep link data is not passed in either case, but maintaining continuity between the operating systems seems to be impossible. The Branch SDK has no control over the device-level behavior on URLs.

Furthermore, I was able to get in-app deep linking to pass data in some cases, but not all. In the case were deep link data was passed, the user was still ejected to Safari first which is still not a good user experience. 
```
[fails] iOS https://cordova.app.link/E31e7cP47H
[works] iOS https://cordova.app.link/E31e7cP47H?$ios_deepview=branch_default
[works] iOS https://cordova.app.link/E31e7cP47H?$uri_redirect_mode=1
[fails] Android https://cordova.app.link/E31e7cP47H
[fails] Android https://cordova.app.link/E31e7cP47H?$ios_deepview=branch_default
[fails] Android https://cordova.app.link/E31e7cP47H?$uri_redirect_mode=1
```

Overall, this appears to be a complicated problem in which the device controls how URLs are handled within the app. Since the Branch SDK cannot control the device-level behavior, we have to, unfortunately, conclude that Branch does not support in-app deep linking. We still strive to bring users into your app through deep links. However, once they are inside your app, our deep links cannot bring a user into an app which they are already in.

I apologize for this inconvenience.

**Comment by YaroslavG** [comment]
@ethanneff 
Thank for your answer

**Comment by ethanneff** [comment]
I'm reviving this issue since we have recently added more capabilities to our forced open ($uri_redirct_mode) on the link service side. 

As of right now, the following is supported by the Branch Cordova SDK:
* [x] out-of-app click of a deep link into your app
* [x] in-app click of a deep link to another app
* [ ] in-app click of a deep link to the same app

Clicking on a deep link within your app will still eject the user outside the app (controlled by the device), but Branch should be able to successfully navigate back into the app. 

I am going to try to get an engineer on the backend to look into this. We should be able to modify our deep link redirection logic to force open the user back into the app.

**Comment by aless673** [comment]
@ethanneff my issue #430 was about initSession not firing. Opening deeplink inside app works fine (going out / going back) but the event does not fire.

**Comment by gregor-srdic** [comment]
I think I have a similar problem:
If my app is closed, and I click on branch link in my email, my app opens and branch init handler is invoked properly.
But if my app is already open, and I switch to email client and click the same branch link there, my app is also opened (brought to front) but the **branch init is not called**. 
I really hope this is not how it is supposed to be, how could you ever have any consistency for the user in this case? :S
I am using Android 7.1 on Galaxy S8

**Comment by gregor-srdic** [comment]
I apologise, my problem was I was not calling `branch.initSession` on resume event.
