### ISSUE TITLE
Inquiry:  cordova-deep-link-plugin and cordova-ionic-phonegap-branch-deep-linking

### ISSUE THREAD

**Issue by billqian99** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#401]
Hi,

I have the following question, for which I am deeply grateful if you can let me know some details.

I'd like to use Google Firebase authentication plugin (https://github.com/firebase/firebaseui-web) to enable login with Google account.  However the plugin seems to require cordova-deep-link-plugin, which is not compatible with Branch deep linking.  

Can you please be more specific where the incompatibility is and whether it can still work out for the above use case?  Enabling Google login, or even Facebook/Twitter seems to be very beneficial to acquire new users.

Thanks,

Bill

**Comment by ethanneff** [comment]
Hello!

[FirebaseUI](https://github.com/firebase/firebaseui-web) should work with our [Branch Cordova SDK](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking). 

The primary reason for the incompatibility plugins is to make developers aware that these plugins tend to override the deep linking settings configured by our plugin (Associated Domains for iOS and Intent Filters for Android). This will prevent deep link data from flowing into your app. Since the 
[FirebaseUI](https://github.com/firebase/firebaseui-web) does not explicitly rely on deep linking, I do not think it will collide with our plugin in a negative way.

**Comment by billqian99** [comment]
Hi,

Thanks for the update.  Appreciate it very much.  I will give it a try and let you know.

Bill
