### ISSUE TITLE
incorrect Branch link generated by iOS device from within China

### ISSUE THREAD

**Issue by billqian99** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#423]
HI, 

My app user in China with iPhone generated a Branch link that doesn't look correct.  See the attached image named BranchLinkChina.png
![branchlinkchina](https://user-images.githubusercontent.com/12097517/35473463-00a31434-034f-11e8-8e50-e67bbde19b9b.png)

However, the link itself works fine while clicked through a device in US.

As reference the link generated in US looks like the following.
<img width="346" alt="branchlinkus" src="https://user-images.githubusercontent.com/12097517/35473480-362ad178-034f-11e8-8279-06a6e344532e.png">

What might be the reason for the discrepancies and how to address them?

Thanks so much for looking into it.

Bill

**Comment by ethanneff** [comment]
Hello Bill!

We have seen problems before in the past when it comes to China. Sometimes the Chines' firewall completely blocks the links from working, sometimes the app does not use the Apple App Store so they block deep linking (because it can potentially fallback to the Apple App Store), and sometimes the app does not recognize the app.link link domain so the link is unclickable. 

I have a feeling this issue is related to the last one. Is there any way you can find out which app the user was using when trying to click on the deep link?

Thanks,

**Comment by billqian99** [comment]
Hi Ethan,

Thanks for looking into the post.  

The user generated the link through my iOS app Word Transformer and shared the link with me through WeChat.

Myself is in US and clicking the link seems fine.  However it doesn't look normal as title/icon are missing.

Thanks,

Bill

**Comment by ethanneff** [comment]
Hey Bill, 

My assumption was wrong. WeChat recognizes the app.link link domain and the link is clickable. Additionally, I tested a few more links in WeChat, and they seem to behave normally (link click -> open app -> pass data). 
![a](https://user-images.githubusercontent.com/2933593/35538835-129d3f28-0504-11e8-973b-d17344f0107a.gif)

WeChat does need an intermediary step of opening Safari since the WeChat app blocks Universal Linking and URI redirects as seen above. This intermediary screen is handled on our end - the user just needs to follow the steps.

I have a feeling there may be some nuances with the Chinese version of WeChat vs the US version. I am not able to get the deep link images or title to show either. 

I will try my best to get a Chinese version of the app to debug.

**Comment by billqian99** [comment]
Hi Ethan,

Thanks for your effort looking into it.  Really appreciate it!

Bill
