### ISSUE TITLE
Subscribe for events while the app is open

### ISSUE THREAD

**Issue by rodrigoreal** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#426]
Hey there, is there any way i can subscribe for events while the app is open?
I've tried to use some events from the ionic platform:
```
this.platform.resume.subscribe(() => {
        branch.initSession((data) => {
          if (data['+clicked_branch_link']) {
            // read deep link data on click
            alert('Deep Link Data: ' + JSON.stringify(data));
          }
        });
      });
```
But it will only work if the app is in the background and is open.
I wanted something like the react native:
```
import branch from 'react-native-branch'

branch.subscribe(({ error, params }) => {
  if (error) {
    console.error('Error from Branch: ' + error)
    return
  }

  // params will never be null if error is null

  if (params['+non_branch_link']) {
    const nonBranchUrl = params['+non_branch_link']
    // Route non-Branch URL if appropriate.
    return
  }

  if (!params['+clicked_branch_link']) {
    // Indicates initialization success and some other conditions.
    // No link was opened.
    return
  }

  // A Branch link was opened.
  // Route link based on data in params.
})
```

**Comment by ethanneff** [comment]
Hello @rodrigoreal,

I am not too sure I understand the use case. If the app is already open, how could deep link information enter the app?  Deep links should cause the app to open - which is why the Branch handler is located in the device's `onResume` and `onDeviceReady` calls. These are the entry points into the app, and the entry points for deep link caused app opens.

Additionally, I am also concerned with multiple subscribe calls within the application. This could lead to race conditions where deep link data never reaches the user. 

Can you please elaborate on why you need this feature?

Thanks,

**Comment by rodrigoreal** [comment]
With a bit more search i found [this issue ](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/392), with is exactly my problem.
I'm trying to use branch with intercom messenger, so i would like to send the user a link inside the chat and redirect the user to the specific content on the app.
