### ISSUE TITLE
Cannot find module 'xml2js'

### ISSUE THREAD

**Issue by alejandromagnorsky** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#429]
I'm trying to build a project that contains the latest version (v2.6.23) of this plugin and I'm getting the error "Error: Cannot find module 'xml2js'". If I run npm install `xml2js` it prompts me the same message but with `node-compare-version` and lastly with `mkpath`. I am using node v8.9.3 and cordova v7.1.0.

**Comment by ethanneff** [comment]
Hello @alejandromagnorsky,

That error typically happens when the SDK failed to install all the dependencies. This failure could be caused by a faulty internet connection or bad response from the NPM network.

I would recommend reinstalling the Branch Cordova SDK. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to reinstall. I would then follow this [integration guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#getting-started) to make sure your config and testing are correct.

Let me know how it goes.

Thanks,

**Comment by alejandromagnorsky** [comment]
Sorry, I forgot to reply to your comment after running what you said. Basically, the output does not change. The only way to fix it is to run npm install with the above libraries.
