### ISSUE TITLE
No data is being read when "access_token" is in the query string

### ISSUE THREAD

**Issue by dsmalicsi** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#433]
Hello,
I have recently integrated our app with an Oauth server which returns a query string where "access_token" is a variable. However, it doesn't get through.

Here's the sample:
>token_type=bearer&**access_token**=XXXXXXXXXXXXXXXX&access_token_expires_in=839&tokens_issued_at=1520393802716&state=XXXXXXXXXX`

If I removed the *access_token* parameter or just changed one letter (or mispell it) like **acces_token**, it works.

E.g. 

> token_type=bearer&**acces_token**=XXXXXXXXXXXXXXXX&access_token_expires_in=839&tokens_issued_at=1520393802716&state=XXXXXXXXXX

Could it possibly be a reserved or filtered word? We don't have control on the 3rd party API server, any suggestions to work around this issue aside from creating another server which parses the returned URL? Thanks!

**Comment by ethanneff** [comment]
Hello @dsmalicsi,

Yes, you are correct. 

We have filters on our gateway which prevents partners from sending confidential data. We do this for security reasons. We don't want partners accidentally send us plain text passwords, private tokens, etc. This could compromise us as well as your users.

Since Branch deep links can be shared quite easily, we typically don't recommend passing sensitive data through them. 

Can you please explain your use case for passing access_tokens? This will give us a better idea of your user flow with deep links. Maybe we need to make changes in our backend, or maybe we can offer an alternative solution to use in your app.  

If you want to speak more confidentially, feel free to contact us at integrations@branch.io. 

Thanks,

**Comment by ethanneff** [comment]
Hello again,

Unfortunately, after piloting the program for a few months, we have decided internally to keep the change. Keywords such as `access_token` and `password` will be blocked by our backend. The security risk to our data is too high to allow the values to flow through our system.

Your best bet is to encapsulate your query strings inside the deep link. You can do this through middleware such as the [Web SDK](https://docs.branch.io/pages/web/integrate/#create-deep-link) or [HTTP API](https://docs.branch.io/pages/apps/api/). Once encapsulated, your deep link data can flow through into your app.

Again, I apologize for this inconvenience. 

Best,
