### ISSUE TITLE
Just can not navigate to a particular page within the app. Only implementing it for android. Haven't tried it for IOS

### ISSUE THREAD

**Issue by soumyaRauth** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#441]
Implementation of navigating to a particular page within the app seems pretty tricky. When I click on the link it always goes to the default root page. But what would be the recommended process to navigate to a particular page within the app. My personal view is that the documentation should be more detailed. Thank you.

**Comment by ethanneff** [comment]
The default root page will always load first. Once you get deep link data from within `Branch.initSession()` (https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#read-deep-link), you can then use that deep link data to navigate to a specific page (https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#navigate-to-content). There is a delay whenever `Branch.initSession()` gets data because it needs to make a connection to the Branch servers to fingerprint the link click and send the correct data. 

If no data is coming from your `Branch.initSession()`, I recommend double-checking the integration guide (https://docs.branch.io/pages/apps/cordova-phonegap-ionic/#integrate-branch)
