### ISSUE TITLE
DeepLinkHandler is not defined

### ISSUE THREAD

**Issue by csotomon** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#451]
After updating to 2.7.0 ha got this error.

![screenshot_20180430-161243](https://user-images.githubusercontent.com/9087039/39450892-71d7de00-4c92-11e8-98f9-48f1c81df80d.png)

**Comment by ethanneff** [comment]
Hello,

I apologize. This version should have been 3.0.0 instead of 2.7.0 since it had a breaking change: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/7a4cf3895ce26b6a85c805e67212289648d16493. Our continuous integration did not handle the versioning correctly. 

The new way to read deep link data is through a promise off of `Branch.initSession().then(data)`. The function `DeepLinkHandler` is no longer defined. [You can read more about how to make this change here](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#migrating-branch-cordova-sdk-from-v25-to-v27), or you can revert to the previous version of the Branch Cordova SDK.

I appologize again for this inconvience.

**Comment by csotomon** [comment]
Ok, I'll return to 2.6.24 version and i'll wait for the new npm package.

**Comment by Luro91** [comment]
Hi @ethanneff 
the error is still printed in the console on Android even when we are using a promise.

**Comment by ethanneff** [comment]
Hello again,

This may be a file rename issue with the latest version. Can you please follow this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to make sure you clear the Branch Cordova SDK and then reinstall it?

**Comment by Luro91** [comment]
It also happens when I reinstall the complete Cordova project completly. 
Can it be related to this line?
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/blob/master/src/android/io/branch/BranchSDK.java#L834

**Comment by ethanneff** [comment]
Yes! Good find. I have just updated the Branch Cordova SDK. I would recommend updating to the latest version `3.0.0`. You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update Branch Cordova SDK.

This version finally represents the breaking change (`3.0.0` instead of `2.7.0+`). Additionally, I am in the process of deprecating `2.7.0+` since this version could cause confusion and headache.

Again, I apologize for all this convenience. 

Thanks,
