### ISSUE TITLE
Commit 7a4cf38 was a breaking change, semver should be 3.0

### ISSUE THREAD

**Issue by ceautery** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#457]
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/7a4cf3895ce26b6a85c805e67212289648d16493 changed how initSession needs to be called from the client. This is going to surprise people who rebuild their plugins from scratch and find deep linking broken.

Can we update the release version to 3.0 instead of 2.7?

**Comment by ethanneff** [comment]
Yes. I have found the bug in the continuous integration. I'll release 3 today and remove 2.7 to prevent any future confusion.

**Comment by ceautery** [comment]
Great! Thanks for the quick response.

**Comment by ethanneff** [comment]
npm v3.0.0 has been released. npm v2.7.0 and v2.7.1 have been deprecated (because they contained breaking changes)

You can use this [guide](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#compiling-updating-the-branch-sdk) to update Branch Cordova SDK.

Thank you for bringing this to my attention.
